src/components/Footer/index.jsx
src/components/Footer/s.module.scss
src/components/Layout/index.jsx

Dubious implementation.
Please review.

Add footer to address issue #10 

---

README.md

Unsure if this is the correct process but it's what made it work for me

Update README.md to set up GitHub PAT for `gatsby-source-graphql`

---

src/components/Footer/s.module.scss
src/components/Layout/s.module.scss
src/pages/styles.module.scss

Did you want text on both the left and right of the footer to align top? If so I can make changes. For now, it's aligned centre.

Better footer

---

src/components/Layout/s.module.scss

Centralise rendered tweet block

---

content/meetups/1.md
gatsby-node.js
package.json
src/components/Footer/s.module.scss
src/components/Layout/index.jsx
src/components/Layout/s.module.scss
src/pages/index.jsx
src/templates/Meetup/index.jsx
src/templates/Meetup/s.module.scss
yarn.lock

@thchia fyi, PRing this for easier review, but i'll merge it for now
any changes are welcome :)

feat: meetup pages with simple presentation layout

---

README.md
package.json
src/templates/Meetup/index.jsx
src/templates/Meetup/s.module.scss
src/utils/remote.js
yarn.lock

feat: better slide control

---

content/meetups/2.md

Update for 16.9

---

content/meetups/5.md
src/pages/index.jsx
src/templates/Meetup/index.jsx

add sponsors list and change "venue sponsor" to "venue"

---

content/meetups/3.md

I am being gratuitous with my PRs #hacktoberfest #noshame.

Added talk 23

---

content/meetups/3.md

Escaped the pound character.

---

content/meetups/3.md
content/meetups/4.md

Address my over-eager merging in #45

Moved new interesting read to next meetup

---

gatsby-config.js
package.json
start.js

Hi @thchia , @wgao19 , I've moved env require to gatsby-config

Resolves: #47 Move env config import to gatsby-config

---

src/pages/index.jsx
src/pages/s.module.scss

- sort talks by descending create order
- use issue "closed" to decide whether talk is upcoming or not
addresses #41 
cc @huijing

display a badge for upcoming talks

---

.gitpod.yml

Added gitpod configuration which enables anyone to contribute with zero setup in their local machine.
Just open the repo on the gitpod and start coding.
Refer more about gitpod [here](https://www.gitpod.io/).

Added initial commands in gitpod

---

gatsby-browser.js

this should fix #70, let's check preview deploy

properly replace hydrate function

---

gatsby-browser.js

fix duplicated content on client side rendering

---

gatsby-browser.js

properly replace hydrate function (did i use this title before?)

---

src/pages/s.module.scss

Please reject if you want to keep the gap.
It's just me being opinionated about white space.

Fix for #83 - unsightly gap between asides

---

src/components/Footer/s.module.scss

Fix breakpoint to deal with more friends of RK

---

src/components/Footer/s.module.scss
src/pages/s.module.scss

Addresses issue #88 
Also accidentally added commit for footer icon animation to this PR.

Fix aside implementation not catering for excessively long event title

---

src/components/Layout/index.jsx
src/templates/Meetup/index.jsx

logo not showing up in meetup pages because url off in the meta tag

fix: meetup page seo

---

package.json
src/components/Footer/s.module.scss
src/components/Layout/s.module.scss
src/pages/s.module.scss

Will make another commit once there is content inside the upcoming talks component (currently empty).

Addresses #110 (broken layout on IE)
